task: training

method: "MD_MWER"

seed: 10

device: "cuda:0"

train_feature:
  - hyps_token_ids
train_feature_path: 
  - "../espnet_data/alfred/train/hyps_text.json"
dev_feature:
  - hyps_token_ids
dev_feature_path: 
  - "../espnet_data/alfred/dev/hyps_text.json"

checkpoint_path: "result/MD_MWER/checkpoint_3.pth"
output_path: "result/MD_MWER"

# the unit of batch size is utterence
# if batch_size = m, means m*n-best hypotheses in one batch
batch_size: 3

# if you don't want to process too much data (like for debugging)
# you can set this value to a small number.
max_utt: 10
n_best: 10

dataloader:
  num_worker: 5

model:
  bert: "bert-base-chinese"