actions:
  - scoring

# training actions
train:
  type: "MD_MWER"
  device: "cuda:0"
  model: "bert-base-chinese"
  train_am_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/train.am.json"
  train_lm_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/domain_adaptation_training/train.lm.json"
  dev_am_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
  dev_lm_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/domain_adaptation_training/dev.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MD_MWER"
  MD_loss_weight: 0.0001
  n_best: 15
  max_utts: 999999
  max_seq_len: 50
  batch_size: 10
  epoch: 10
  num_worker: 5

# inference actions
scoring:
  type: "MD_MWER"
  device: "cuda:0"
  model: "bert-base-chinese"
  model_weight_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MD_MWER/checkpoint_4.pth"
  asr_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MD_MWER/test.lm.json"
  n_best: 2
  max_utts: 2
  max_seq_len: 50
  batch_size: 100
  num_worker: 3

rescoring:
  dev_asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\dev.am.json"
  dev_lm_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training\\dev.lm.json"
  test_asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  test_lm_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training\\test.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MD_MWER/test.am_lm.json"
  max_utts: 3