exp_tag: "MD_MWED training"

actions:
  - train

# training actions
train:
  type: "MD_MWED"
  device: "cuda:0"
  model: "bert-base-chinese"
  model_weight_path:
  train_am_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/train.am.json"
  train_lm_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/domain_adaptation_training/train.lm.json"
  dev_am_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
  dev_lm_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/domain_adaptation_training/dev.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MD_MWED"
  MD_loss_weight: 0.0001
  n_best: 15
  max_utts: 9999999
  max_seq_len: 50
  batch_size: 10
  epoch: 10
  num_worker: 5

# inference actions
scoring:
  type: "token_level"
  device: "cuda:0"
  model: "bert-base-chinese"
  model_weight_path: "/home/chkuo/chkuo/experiment/rescoring/result/PLL_train_on_trainset/checkpoint_10.pth"
  asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/train.am.json"
  text_type: "hyp"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/result/MLM_distill_no_discriminative/train.lm.json"
  max_utts: 999999
  batch_size: 100

rescoring:
  asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"
  lm_data_path: "/home/chkuo/chkuo/experiment/rescoring/result/test.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"