exp_tag: "MWER training"

actions:
  - scoring

# training actions
train:
  type: "MWER"
  device: "cuda:0"
  model: "bert-base-chinese"
  train_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/train.am.json"
  dev_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MWER2"
  n_best: 15
  max_utts: 999999
  max_seq_len: 50
  batch_size: 7
  epoch: 10

# inference actions
scoring:
  type: "MWER"
  device: "cuda:0"
  model: "bert-base-chinese"
  model_weight_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MWER2/checkpoint_10.pth"
  asr_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MWER2/test.lm.json"
  n_best: 15
  max_utts: 10
  batch_size: 300

rescoring:
  dev_asr_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
  dev_lm_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MWER2/test.lm.json"
  test_asr_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/test.am.json"
  test_lm_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MWER2/test.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/MWER2/test.am_lm.json"
  max_utts: 9999999