task: inference

method: "one_hyp"

seed: 10

device: "cuda:0"

dev_feature:
  - hyps_token_ids
dev_feature_path: 
  - "../espnet_data/alfred/dev/hyps_text.json"
dev_output_format: "../espnet_data/alfred/dev/ref_text.json"

test_feature:
  - hyps_token_ids
test_feature_path: 
  - "../espnet_data/alfred/test/hyps_text.json"
test_output_format: "../espnet_data/alfred/test/ref_text.json"

checkpoint_path: "result/one_hyp/checkpoint_4.pth"
output_path: "result/one_hyp"

# the unit of batch size is utterence
# if batch_size = m, means m*n-best hypotheses in one batch
batch_size: 128

# if you don't want to process too much data (like for debugging)
# you can set this value to a small number.
max_utt: 9999999
n_best: 1

dataloader:
  shuffle: False
  num_worker: 5

model:
  bart: "fnlp/bart-base-chinese"

resume: 
  start_from: 
  checkpoint_path: 