action: train

method: "bertsem"

setting:
  # path:
  train_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/train.am.json"
  dev_data_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/data/dev.am.json"
  output_path: "/home/chkuo/chkuo/experiment/ASR-Rescoring/result/sem"

  # model
  bert: "bert-base-chinese"
  dropout: 0.3

  device: "cuda:0"
  lr: 0.00001
  seed: 10
  shuffle: True
  n_best: 15
  max_utts: 999999
  max_seq_len: 100
  batch_size: 100
  epoch: 10
  num_worker: 5