task: training

method: "top_one_anchor"

seed: 10

lr: 0.00001
epoch: 10
device: "cpu"

train_feature:
  - ref_token_ids
  - hyps_token_ids
train_feature_path: 
  - "../espnet_data/alfred/test/ref_text.json"
  - "../espnet_data/alfred/test/hyps_text.json"
dev_feature:
  - ref_token_ids
  - hyps_token_ids
dev_feature_path: 
  - "../espnet_data/alfred/test/ref_text.json"
  - "../espnet_data/alfred/test/hyps_text.json"

output_path: "result/ref_anchor"

# the unit of batch size is utterence
# if batch_size = m, means m*n-best hypotheses in one batch
batch_size: 2

# if you don't want to process too much data (like for debugging)
# you can set this value to a small number.
max_utt: 2
n_best: 2

dataloader:
  shuffle: False
  num_worker: 5

model:
  bert: "bert-base-chinese"

resume: 
  start_from: 
  checkpoint_path: 