task: training

method: "top_one_anchor"

seed: 10

lr: 0.00001
epoch: 2
device: "cpu"

train_feature:
  - ref_text
  - hyp_text
train_feature_path: 
  - "../espnet_data/alfred/test/ref_text.json"
  - "../espnet_data/alfred/test/hyps_text.json"
dev_feature:
  - ref_text
  - hyp_text
dev_feature_path: 
  - "../espnet_data/alfred/test/ref_text.json"
  - "../espnet_data/alfred/test/hyps_text.json"

output_path: "result/top_one_anchor"

# the unit of batch size is utterence
# if batch_size = m, means m*n-best hypotheses in one batch
batch_size: 2

# if you don't want to process too much data (like for debugging)
# you can set this value to a small number.
max_utt: 10
n_best: 3

dataloader:
  shuffle: False
  num_worker: 5

model:
  bert: "bert-base-chinese"

resume: 
  start_from: 
  checkpoint_path: 