action: train

method: "bertsem"

setting:
  # path:
  train_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  dev_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\sem"

  # model
  bert: "bert-base-chinese"
  dropout: 0.3

  device: "cpu"
  lr: 0.00001
  seed: 10
  shuffle: True
  n_best: 3
  max_utts: 5
  max_seq_len: 100
  batch_size: 100
  epoch: 2
  num_worker: 5