exp_tag: "generate_train_dataset(LM_score) to train distill model"

actions:
  - scoring

# training actions
train:
  type: "domain_adaptation"
  device: "cuda:0"
  model: "bert-base-chinese"
  train_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/train.am.json"
  text_type: "ref"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/result/2022_2_24/"
  max_utts: 9999999
  max_seq_len: 50
  batch_size: 100
  epoch: 10

# inference actions
scoring:
  type: "token_level"
  device: "cuda"
  model: "bert-base-chinese"
  model_weight_path: "/home/chkuo/chkuo/experiment/rescoring/result/PLL_train_on_trainset/checkpoint_10.pth"
  asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/train.am.json"
  text_type: "hyp"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/result/MLM_distill_no_discriminative/train.lm.json"
  max_utts: 999999
  batch_size: 100

rescoring:
  asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"
  lm_data_path: "/home/chkuo/chkuo/experiment/rescoring/result/test.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"