
device: "cuda:0"

utility_function: "cer"

dev_feature:
  - ref_text
  - hyps_text
dev_feature_path:
  - "../espnet_data/alfred/dev/ref_text.json"
  - "../espnet_data/alfred/dev/hyps_text.json"
dev_output_format: "../espnet_data/alfred/dev/hyps_score.json"

test_feature:
  - ref_text
  - hyps_text
test_feature_path: 
  - "../espnet_data/alfred/test/ref_text.json"
  - "../espnet_data/alfred/test/hyps_text.json"
test_output_format: "../espnet_data/alfred/test/hyps_score.json"

output_path: "result/"

batch_size: 128

# if you don't want to process too much data (like for debugging)
# you can set this value to a small number.
max_utt: 99999999
n_best: 10

language: "zh"
