dev_file: "../../data/dev.am.json"
test_file: "../../data/test.am.json"

output_path: "../../result/MBR"

utility_function: "bertscore"
language: "zh"
device: "cuda:0"
batch_size: 256
max_utts: 999999
n_best: 15
