exp_tag: "error detection training"

actions:
  - scoring

# training actions
train:
  type: "error_detection_training"
  device: "cpu"
  model: "bert-base-chinese"
  train_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  dev_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training"
  max_utts: 10
  max_seq_len: 50
  batch_size: 100
  epoch: 10

# inference actions
scoring:
  type: "error_detection_training"
  device: "cpu"
  model: "bert-base-chinese"
  model_weight_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training\\checkpoint_10.pth"
  asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  text_type: "hyp"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training\\train.lm.json"
  max_utts: 10
  batch_size: 100

rescoring:
  asr_data_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"
  lm_data_path: "/home/chkuo/chkuo/experiment/rescoring/result/test.lm.json"
  output_path: "/home/chkuo/chkuo/experiment/rescoring/data/test.am.json"