actions:
  - train

# training actions
train:
  type: "MD_MWER"
  device: "cpu"
  model: "bert-base-chinese"
  train_am_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  train_lm_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\test.lm.json"
  dev_am_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  dev_lm_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\domain_adaptation_training\\test.lm.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\MD_MWER"
  MD_loss_weight: 0.0001
  n_best: 2
  max_utts: 2
  max_seq_len: 50
  batch_size: 100
  epoch: 2
  num_worker: 3

# inference actions
scoring:
  type: "MD_MWER"
  device: "cpu"
  model: "bert-base-chinese"
  model_weight_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\MD_MWER\\checkpoint_1.pth"
  asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\MD_MWER\\test.lm.json"
  n_best: 2
  max_utts: 2
  max_seq_len: 50
  batch_size: 100
  num_worker: 3

rescoring:
  dev_asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\dev.am.json"
  dev_lm_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training\\dev.lm.json"
  test_asr_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\data\\test.am.json"
  test_lm_data_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training\\test.lm.json"
  output_path: "D:\\NTUST\\NLP\\experiments\\ASR-Rescoring\\result\\error_detection_training\\test.am_lm.json"
  max_utts: 3